/*

*/
import java.util.*;
class TestClass {
	public static void main(String args[] ) throws Exception {
		Scanner in=new Scanner(System.in);
		int T=in.nextInt();
		for(int i=0;i<T;i++){
			int xe=in.nextInt();
			int ye=in.nextInt();
			char d=in.next().charAt(0);
			int n=in.nextInt();
			int flag=0;
			int xa=0,ya=0;
			char da=0;
			float x=0;
			for(int j=0;j<n;j++){
				xa=in.nextInt();
				ya=in.nextInt();
				da=in.next().charAt(0);
				if(xe==xa&&ye==ya){
					continue;
				}
				if(flag==0){
					if(d=='U'&&da=='U'){
						if(ye>ya){
							x=(ye-ya);
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='D'&&da=='D'){
						if(ye<ya){
							x=(ya-ye);
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='L'&&da=='L'){
						if(xe<xa){
							x=(xa-xe);
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='R'&&da=='R'){
						if(xe>xa){
							x=(xe-xa);
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='R'&&da=='U'){
						if(xe>xa&&ya>ye){
							x=(float)(xe-xa+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='R'&&da=='D'){
						if(xe>xa&&ya<ye){
							x=(float)(xe-xa+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='U'&&da=='R'){
						if(xe<xa&&ya>ye){
							x=(float)(xa-xe+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='U'&&da=='L'){
						if(xe>xa&&ya>ye){
							x=(float)(xa-xe+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='D'&&da=='R'){
						if(xe<xa&&ya<ye){
							x=(float)(xa-xe+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='D'&&da=='L'){
						if(xe>xa&&ya<ye){
							x=(float)(xa-xe+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='L'&&da=='U'){
						if(xe<xa&&ya>ye){
							x=(float)(xe-xa+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
					if(d=='L'&&da=='D'){
						if(xe<xa&&ya<ye){
							x=(float)(xe-xa+ye-ya)/(float)2;
							flag=1;
						}else{
							continue;
						}
					}
				}
				else{
					if(d=='U'&&da=='U'){
						if(ye>ya&&x>(ye-ya)){
							x=(ye-ya);
						}else{
							continue;
						}
					}
					if(d=='D'&&da=='D'){
						if(ye<ya&&x>(ya-ye)){
							x=(ya-ye);
						}else{
							continue;
						}
					}
					if(d=='L'&&da=='L'){
						if(xe<xa&&x>(xa-xe)){
							x=(xa-xe);
						}else{
							continue;
						}
					}
					if(d=='R'&&da=='R'){
						if(xe>xa&&x>(xe-xa)){
							x=(xe-xa);
						}else{
							continue;
						}
					}
					if(d=='R'&&da=='U'){
						if(xe>xa&&ya>ye&&x>(float)(xe-xa+ye-ya)/(float)2){
							x=(float)(xe-xa+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
					if(d=='R'&&da=='D'){
						if(xe>xa&&ya<ye&&x>(float)(xe-xa+ye-ya)/(float)2){
							x=(float)(xe-xa+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
					if(d=='U'&&da=='R'){
						if(xe<xa&&ya>ye&&x>(float)(xa-xe+ye-ya)/(float)2){
							x=(float)(xa-xe+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
					if(d=='U'&&da=='L'){
						if(xe>xa&&ya>ye&&x>(float)(xa-xe+ye-ya)/(float)2){
							x=(float)(xa-xe+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
					if(d=='D'&&da=='R'){
						if(xe<xa&&ya<ye&&x>(float)(xa-xe+ye-ya)/(float)2){
							x=(float)(xa-xe+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
					if(d=='D'&&da=='L'){
						if(xe>xa&&ya<ye&&x>(float)(xa-xe+ye-ya)/(float)2){
							x=(float)(xa-xe+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
					if(d=='L'&&da=='U'){
						if(xe<xa&&ya>ye&&x>(float)(xe-xa+ye-ya)/(float)2){
							x=(float)(xe-xa+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
					if(d=='L'&&da=='D'){
						if(xe<xa&&ya<ye&&x>(float)(xe-xa+ye-ya)/(float)2){
							x=(float)(xe-xa+ye-ya)/(float)2;
						}else{
							continue;
						}
					}
				}
			}
			if(flag==0){
				System.out.println("SAFE");
			}
			else{
				System.out.printf("%.1f",x);
				System.out.println("");
			}
		}
    }
}