"""
model.py - It is the script to access codex model via api, feed input in the form of prompts and capture code that will
be generated by model as output
"""

import os
import openai

MODEL_NAME = "code-davinci-002"


def run_model(input_description):

    openai.api_key = os.environ.get("OPENAI_API_KEY")
    response = openai.Completion.create(model=MODEL_NAME, prompt=input_description, temperature=0.7, max_tokens=4000,
                                        top_p=1, frequency_penalty=0, presence_penalty=0)

    return response
